import { execSync, spawn } from "node:child_process"
import fs from "node:fs"
import path from "node:path"

import { claimPorts, releasePorts } from "./worktree-port-registry"

export type PreviewEnv = {
  API_PORT: string
  PORT: string
  CORS_ORIGIN: string
  NEXT_PUBLIC_API_HTTP_URL: string
  NEXT_PUBLIC_API_WS_URL: string
  NEXT_PUBLIC_API_URL: string
  NEXT_PUBLIC_API_BASE_URL: string
  NEXT_PUBLIC_APP_TITLE_PREFIX: string
  SQLITE_PATH: string
  UPLOADS_DIR: string
  RUNTIME_EVENTS_DIR: string
}

export function buildPreviewEnv(input: {
  repoRoot: string
  worktreeName: string
  apiPort: number
  webPort: number
}): PreviewEnv {
  const apiBase = `http://localhost:${input.apiPort}`
  return {
    API_PORT: String(input.apiPort),
    PORT: String(input.webPort),
    CORS_ORIGIN: `http://localhost:${input.webPort}`,
    NEXT_PUBLIC_API_HTTP_URL: apiBase,
    NEXT_PUBLIC_API_WS_URL: `ws://localhost:${input.apiPort}/ws`,
    NEXT_PUBLIC_API_URL: apiBase,
    NEXT_PUBLIC_API_BASE_URL: apiBase,
    NEXT_PUBLIC_APP_TITLE_PREFIX: `[${input.worktreeName}] `,
    SQLITE_PATH: `${input.repoRoot}/.runtime/worktree-preview/data/multi-agent.sqlite`,
    UPLOADS_DIR: `${input.repoRoot}/.agents/acceptance/uploads`,
    RUNTIME_EVENTS_DIR: `${input.repoRoot}/.agents/acceptance/runtime-events`,
  }
}

export function buildDotenvContent(env: PreviewEnv): string {
  const keys: (keyof PreviewEnv)[] = [
    "NEXT_PUBLIC_API_HTTP_URL",
    "NEXT_PUBLIC_API_WS_URL",
    "NEXT_PUBLIC_API_URL",
    "NEXT_PUBLIC_API_BASE_URL",
    "NEXT_PUBLIC_APP_TITLE_PREFIX",
  ]
  const lines = ["# auto-generated by scripts/worktree-preview.ts — removed on exit"]
  for (const key of keys) {
    lines.push(`${key}=${JSON.stringify(env[key])}`)
  }
  return lines.join("\n") + "\n"
}

export type DotenvHandle = {
  targetPath: string
  backupPath: string | null
}

export function prepareDotenv(targetPath: string, content: string): DotenvHandle {
  let backupPath: string | null = null
  if (fs.existsSync(targetPath)) {
    backupPath = `${targetPath}.backup-by-preview`
    fs.renameSync(targetPath, backupPath)
  }
  fs.writeFileSync(targetPath, content)
  return { targetPath, backupPath }
}

export function restoreDotenv(handle: DotenvHandle): void {
  try {
    fs.unlinkSync(handle.targetPath)
  } catch {
    // tolerate already-removed preview file
  }
  if (handle.backupPath && fs.existsSync(handle.backupPath)) {
    fs.renameSync(handle.backupPath, handle.targetPath)
  }
}

export type ShutdownPreviewOpts = {
  registryPath: string
  worktreeName: string
  dotenvHandle: DotenvHandle | null
  killers: Array<() => void>
}

// Re-review P1 (2026-04-20): the SIGINT handler used to be sync + fire-and-forget
// `void releasePorts(...).catch(() => {})`, then `process.exit(0)` — so Ctrl+C
// killed the process before the release Promise ever ran its mkdir-unlock, and
// `.worktree-ports.json` leaked a zombie entry on every preview stop. Shutdown
// must expose an awaitable Promise that only resolves after releasePorts has
// actually landed, so the signal handler can `await` it before exiting.
export async function shutdownPreview(opts: ShutdownPreviewOpts): Promise<void> {
  try {
    await releasePorts(opts.registryPath, opts.worktreeName)
  } catch {
    // best-effort — a stale lock or missing file must not block the shutdown path
  }
  if (opts.dotenvHandle) restoreDotenv(opts.dotenvHandle)
  for (const kill of opts.killers) {
    try {
      kill()
    } catch {
      // tolerate double-kill / already-exited children
    }
  }
}

export type ShutdownController = {
  triggerShutdown: () => Promise<void>
}

// Extracted from main() so tests can exercise the signal-handler singleton
// wiring without spawning a real preview (SIGINT + SIGTERM racing must still
// release the port only once — see re-review non-blocking follow-up).
export function createShutdownController(opts: ShutdownPreviewOpts): ShutdownController {
  let shutdownPromise: Promise<void> | null = null
  return {
    triggerShutdown: () => {
      if (!shutdownPromise) {
        shutdownPromise = shutdownPreview(opts)
      }
      return shutdownPromise
    },
  }
}

export function formatPreviewBanner(input: {
  worktreeName: string
  webPort: number
  apiPort: number
  tty: boolean
}): string {
  const webUrl = `http://localhost:${input.webPort}`
  const apiUrl = `http://localhost:${input.apiPort}`
  const keyLine = `worktree ${input.worktreeName} preview: localhost:${input.webPort}`

  if (!input.tty) {
    return `worktree ${input.worktreeName} preview: web=${webUrl} api=${apiUrl}`
  }

  const title = `worktree ${input.worktreeName} preview`
  const lines = [
    title,
    `  web: ${webUrl}`,
    `  api: ${apiUrl}`,
    keyLine,
  ]
  const width = Math.max(...lines.map((l) => l.length)) + 2
  const border = "+".padEnd(width + 2, "-") + "+"
  const padded = lines.map((l) => `| ${l.padEnd(width - 1)}|`).join("\n")
  return [border, padded, border].join("\n")
}

function isMainModule(): boolean {
  const entry = process.argv[1]
  if (!entry) return false
  const here = new URL(import.meta.url).pathname.replace(/^\//, "")
  const normalized = path.resolve(entry).replace(/\\/g, "/")
  return normalized === here.replace(/\\/g, "/")
}

async function main(): Promise<void> {
  const worktreeRoot = process.cwd()
  const worktreeName = execSync("git rev-parse --abbrev-ref HEAD", {
    cwd: worktreeRoot,
  })
    .toString()
    .trim()

  const mainRepoRoot = execSync("git rev-parse --path-format=absolute --git-common-dir", {
    cwd: worktreeRoot,
  })
    .toString()
    .trim()
    .replace(/\/\.git$/, "")
    .replace(/\\\.git$/, "")
  const registryPath = path.join(mainRepoRoot, ".worktree-ports.json")

  const entry = await claimPorts(registryPath, worktreeName)
  const env = buildPreviewEnv({
    repoRoot: worktreeRoot.replace(/\\/g, "/"),
    worktreeName,
    apiPort: entry.apiPort,
    webPort: entry.webPort,
  })

  fs.mkdirSync(path.dirname(env.SQLITE_PATH), { recursive: true })
  fs.mkdirSync(env.UPLOADS_DIR, { recursive: true })
  fs.mkdirSync(env.RUNTIME_EVENTS_DIR, { recursive: true })

  const dotenvPath = path.join(worktreeRoot, ".env.development.local")
  const dotenvHandle = prepareDotenv(dotenvPath, buildDotenvContent(env))

  const banner = formatPreviewBanner({
    worktreeName,
    webPort: entry.webPort,
    apiPort: entry.apiPort,
    tty: Boolean(process.stdout.isTTY),
  })
  console.log(banner)

  const childEnv = { ...process.env, ...env }
  const api = spawn("pnpm", ["dev:api"], {
    cwd: worktreeRoot,
    env: childEnv,
    stdio: "inherit",
    shell: true,
  })
  const web = spawn("pnpm", ["dev:web"], {
    cwd: worktreeRoot,
    env: childEnv,
    stdio: "inherit",
    shell: true,
  })

  const { triggerShutdown } = createShutdownController({
    registryPath,
    worktreeName,
    dotenvHandle,
    killers: [() => api.kill(), () => web.kill()],
  })
  const onSignal = (): void => {
    void triggerShutdown().finally(() => process.exit(0))
  }
  process.on("SIGINT", onSignal)
  process.on("SIGTERM", onSignal)
  api.on("exit", () => {
    void triggerShutdown()
  })
  web.on("exit", () => {
    void triggerShutdown()
  })
}

if (isMainModule()) {
  main().catch((err) => {
    console.error(err)
    process.exit(1)
  })
}
